# Generated by Django 3.1.2 on 2021-02-06 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Places', '0001_initial'),
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='base_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Places.charging_station'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.pharmacy'),
        ),
        migrations.AddField(
            model_name='meal',
            name='kitchen_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.kitchen'),
        ),
        migrations.AddField(
            model_name='food_item',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.meal'),
        ),
        migrations.AddField(
            model_name='edge',
            name='nodeA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodeA', to='Items.anchor'),
        ),
        migrations.AddField(
            model_name='edge',
            name='nodeB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodeB', to='Items.anchor'),
        ),
    ]
