# Generated by Django 3.1.2 on 2021-02-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Items', '0001_initial'),
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.pharmacy'),
        ),
        migrations.AddField(
            model_name='meal',
            name='kitchen_d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Places.kitchen'),
        ),
        migrations.AddField(
            model_name='food_item',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.meal'),
        ),
    ]
