# Generated by Django 3.1.2 on 2021-02-05 00:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_auto_20210204_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodeA', to='Items.anchor')),
                ('nodeB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodeB', to='Items.anchor')),
            ],
        ),
    ]
