# Generated by Django 3.1.2 on 2021-02-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_auto_20210205_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
