# Generated by Django 3.1.2 on 2021-02-06 22:05

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.FloatField()),
                ('tempreture', models.FloatField()),
                ('pressure', models.FloatField()),
                ('time_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos/person/'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Department_manager',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.person')),
            ],
            bases=('Person.person',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.person')),
            ],
            bases=('Person.person',),
        ),
        migrations.CreateModel(
            name='Hospital_manager',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.person')),
            ],
            bases=('Person.person',),
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.person')),
                ('start_shift', models.TimeField()),
                ('end_shift', models.TimeField()),
            ],
            bases=('Person.person',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.person')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('child', 'child')], max_length=32)),
                ('age', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
            ],
            bases=('Person.person',),
        ),
        migrations.CreateModel(
            name='Patient_Mate',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.person')),
                ('mobile', models.IntegerField()),
            ],
            bases=('Person.person',),
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Person.person')),
            ],
            bases=('Person.person',),
        ),
    ]
